event_inherited();
taskName = "RELIEVE STRESS";
taskTTC = 2;
taskAction = -100;
taskHunger = 0;
taskStress = -1000;
taskMoney = 0;
taskTrash = 0;
taskStudy = 0;
taskSound = Relax_snd;
requirements = ["hunger2", "0_Stress"];