event_inherited();
taskName = "GO TO WORK";
taskTTC = 1;
taskAction = -800;
taskHunger = 0;
taskStress = 500;
taskMoney = 70;
taskTrash = 0;
taskStudy = 0;
taskSound = GettinMoney_snd;
requirements = ["panic", "hunger3", "exhausted"];